#!/bin/bash

# This script runs the IBIS shell. Python is required.
#
# This script assumes that the supporting library files for the Ibis shell are rooted in /opt/app/ibis
#
# The required directories are:
# /opt/app/workflows/ -- location for worklflows that are generated
# logs/ -- captures logs when Ibis is running
# /opt/app/ibis/ -- containing ibis egg.

# REPO_HOME - directory where this file is present
REPO_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# export git
export GIT_EXEC_PATH=/opt/app/ibis/ibis_lib/git/libexec/git-core
export PATH=${GIT_EXEC_PATH}:${PATH}

OOZIE_URL_DEV='http://fake.dev.oozie:25007/oozie'
OOZIE_URL_INT='http://fake.int.oozie:25007/oozie'
OOZIE_URL_PROD='http://fake.oozie:25007/oozie'

if [[ $(hostname -s) = dev* ]]; then
    # dev
    export OOZIE_URL=${OOZIE_URL_DEV}
elif [[ $(hostname -s) = int* ]]; then
    # int
    export OOZIE_URL=${OOZIE_URL_INT}
elif [[ $(hostname -s) = prod* ]]; then
    # prod
    export OOZIE_URL=${OOZIE_URL_PROD}
else
    if [ -z ${ENV+x} ]
    then
        echo -e "\tError: environment variable 'ENV' not set\n\tDo this -> export ENV='dev'"
        exit 1
    elif [ ${ENV} == 'dev' ]
    then
        # dev
        export OOZIE_URL=${OOZIE_URL_DEV}
    elif [ ${ENV} == 'int' ]
    then
        # int
        export OOZIE_URL=${OOZIE_URL_INT}
    elif [ ${ENV} == 'prod' ]
    then
        # prod
        export OOZIE_URL=${OOZIE_URL_PROD}
    else
        echo -e "Error: Environment variable OOZIE_URL not set!"
        exit 1
    fi
fi

source "$REPO_HOME"/ibis_version.sh

echo "Welcome to...

 ▄█  ▀█████████▄   ▄█     ▄████████
███    ███    ███ ███    ███    ███
███▌   ███    ███ ███▌   ███    █▀
███▌  ▄███▄▄▄██▀  ███▌   ███
███▌ ▀▀███▀▀▀██▄  ███▌ ▀███████████
███    ███    ██▄ ███           ███
███    ███    ███ ███     ▄█    ███
█▀   ▄█████████▀  █▀    ▄████████▀

Version ${IBIS_VERSION}
"

IBIS_EGG_NAME="${IBIS_APP_NAME}-${IBIS_VERSION}-py2.7.egg"

if [ "$1" = "--run-int-tests" ]; then
    source ${REPO_HOME}/ibis_venv/bin/activate
    python ${REPO_HOME}/"${IBIS_EGG_NAME}" "$@"
    let IBIS_EXIT_STATUS=$?
else
    source "${REPO_HOME}"/ibis_venv/bin/activate && "${REPO_HOME}"/"${IBIS_EGG_NAME}" "$@"
    let IBIS_EXIT_STATUS=$?
    python --version
fi

if [ "${IBIS_EXIT_STATUS}" -gt 0 ]; then
    echo -e "Ibis failed!"
    exit 1
fi

deactivate
